services:
  # app
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /var/www

    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
      - httpserver

  # postgreSQL
  db:
    image: mysql:latest
    container_name: dbserver
    restart: always

    ports:
      - "3306:3306"

    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD

    volumes:
      - /var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql:/docker-entrypoint-initdb.d

  # nginx
  httpserver:
    container_name: nginxServer
    image: nginx:alpine
    restart: always
    ports:
      - "7777:7777"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d

volumes:
  postgres:
  cache:
    driver: local