<!-- init header -->
<header class="main-header">
    <div class="menu-container content">
        <div class="logo-container">
            <img class="logo-header" src="/assets/img/logo_header.svg" alt="logo">
        </div>
        <form action="#" class="search-form" >
            <input type="text" name="search" placeholder="Pesquisar cursos...">
            <button type="submit"><img src="/assets/img/search.png" alt="search" width="32" height="32"></button>
        </form>
        <ul class="menu">
            <li>
                <img  class="profile" src="/assets/img/user.png" alt="search" width="50" height="50">
                <span class="welcome_user">
                <span class="welcome">Seja bem-vindo</span>
                <span class="user">Lucas Rodrigues</span>
            </span>
                <div class="dropdown">
                    <button class="btn dropdown-toggle drop-down" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Meus Dados</a></li>
                        <li><a class="dropdown-item" href="#">Sair</a></li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</header>
<!-- end header -->

<!-- init slide -->
<div id="carouselExampleCaptions" class="carousel slide slideshow">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="/assets/img/slide.png" class="d-block w-100 img-slide" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <div class="content-caption">
                    <h3>LOREM IPSUM 1</h3>
                    <p>Lorem Ipsum is simply dummy text of the printing
                        and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
                        when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                    <a href="#"><span>VER CURSO</span></a>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img src="/assets/img/slide.png" class="d-block w-100 img-slide" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <div class="content-caption">
                    <h3>LOREM IPSUM 2</h3>
                    <p>Lorem Ipsum is simply dummy text of the printing
                        and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
                        when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                    <a href="#"><span>VER CURSO</span></a>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img src="/assets/img/slide.png" class="d-block w-100 img-slide" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <div class="content-caption">
                    <h3>LOREM IPSUM 3</h3>
                    <p>Lorem Ipsum is simply dummy text of the printing
                        and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
                        when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                    <a href="#"><span>VER CURSO</span></a>
                </div>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<!-- end slide -->

<!-- init courses -->
<div class="all-courses">
    <div class="title-courses">
        <h3>MEUS CURSOS</h3>
    </div>
    <div class="row courses-list">
        <div class="col-sm-6 col-lg-3 course">
            <div class="card card-course">
                <img src="assets/img/curso-banner.png" class="card-img-top" alt="curso-banner">
                <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn">VER CURSO</a>
                </div>
            </div>
        </div>

        <div class="col-sm-6 col-lg-3 course">
            <div class="card add-course">
                <a href=#>
                    <img src="assets/img/add_course.svg" class="card-img-top" alt="icone para adicionar curso">
                    <span>ADICIONAR</span>
                    <h5>CURSO</h5>
                </a>
            </div>
        </div>

    </div>
</div>
<!-- end coursers -->


