<header class="main-header">
    <div class="menu-container content">
        <div class="logo-container">
            <img src="/assets/img/leo.png" alt="logo">
        </div>
        <form action="#" class="search-form" >
            <input type="text" name="search" placeholder="Pesquisar cursos...">
            <button type="submit"><img src="/assets/img/search.png" alt="search" width="32" height="32"></button>
        </form>
        <ul class="menu">
            <li>
                <span class="profile">
                    <img src="/assets/img/user.png" alt="search" width="32" height="32">
                </span>
                <span class="welcome_user">
                    <span class="welcome">Seja bem-vindo</span>
                    <span class="user">Lucas Rodrigues</span>
                </span>
                <div class="dropdown">
                    <button class="btn dropdown-toggle drop-down" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Meus Dados</a></li>
                        <li><a class="dropdown-item" href="#">Sair</a></li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</header>