<!-- init courses -->
<div class="all-courses">
    <div class="title-courses">
        <h3>MEUS CURSOS</h3>
    </div>
    <div class="row courses-list">

        <?php foreach($this->view->dados as $course) { ?>
            <div class="col-sm-6 col-lg-3 course">
                <div class="card card-course">
                    <img src="storage/banner-course/<?= $course['banner'] ?>" class="card-img-top" alt="curso-banner">
                    <div class="card-body">
                        <h5 class="card-title"><?= $course['title'] ?></h5>
                        <p class="card-text"><?= $course['description'] ?></p>
                        <a class="btn" data-bs-toggle="modal" data-bs-target="#managementCourse" data-action="edit"
                           data-id="<?= $course['id'] ?>"
                           data-title="<?= htmlspecialchars($course['title'], ENT_QUOTES) ?>"
                           data-description="<?= htmlspecialchars($course['description'], ENT_QUOTES) ?>"
                           data-banner="<?= $course['banner'] ?>">VER CURSO</a>
                    </div>
                </div>
            </div>
        <?php } ?>

        <div class="col-sm-6 col-lg-3 course">
            <div class="card add-course">
                <a data-bs-toggle="modal" data-bs-target="#managementCourse" data-action="create">
                    <img src="assets/img/add_course.svg" class="card-img-top" alt="icone para adicionar curso">
                    <span>ADICIONAR</span>
                    <h5>CURSO</h5>
                </a>
            </div>
        </div>

    </div>
</div>
<!-- end coursers -->
