<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Desafio Revvo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="/assets/css/main.css">
</head>
<body>
    <div class="container">
        <?= $this->content() ?>
        <footer class="footer">
            <div class="content-wrapper content">
                <div class="left-content">
                    <article>
                        <div class="container-image">
                            <img class="logo-footer" src="assets/img/logo_footer.svg" alt="logo">
                        </div>
                        <p>Maecenas faucibus molis interdum. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
                    </article>
                </div>
                <div class="right-content">
                    <article>
                        <h2 class="sub-title">// CONTATO</h2>
                        <p>(21) 98756-3434<br>contato@leolearning.com</p>
                    </article>
                    <article>
                        <h2 class="sub-title">// REDES SOCIAIS</h2>
                        <div class="social-icons">
                            <a class="icons icon-youtube"><img class="icons-social" src="assets/img/youtube.png" alt="icon youtube" width="20" height="20"/></a>
                            <a class="icons icon-pinterest"><img class="icons-social" src="assets/img/pinterest.png" alt="icon pinterest" width="20" height="20"/></a>
                            <a class="icons icon-twitter"><img class="icons-social" src="assets/img/twitter.png" alt="icon twitter" width="20" height="20"/></a>
                        </div>
                    </article>
                </div>
            </div>
            <div class="footer-copyright">
                <p>Copyright 2024 - All right reserved.</p>
            </div>
        </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="assets/js/main.js"></script>
</body>
</html>
